#!/usr/bin/env bash
# sdk/.github/scripts/assemble_release_evidence.sh — PRD-028 PR α companion.
#
# Invoked by release.yml after verify-published succeeds. Collects build
# metadata + SBOM digest + SLSA provenance URL + Sigstore bundle ref +
# private-source SHA, writes RELEASE_EVIDENCE.md, and attaches it as a
# GitHub Release asset.
#
# Row schema is forward-compatible with PRD-013 Merkle ledger.
#
# Required environment:
#   GITHUB_REF_NAME         — the sdk-v<X.Y.Z> tag
#   GITHUB_SHA              — the tagged commit SHA on the public repo
#   SDK_VERSION             — X.Y.Z (resolved by release.yml/prepare)
#   IS_RC                   — "true" or "false"
#   SDIST_SHA256            — from release.yml/build
#   WHEEL_SHA256            — from release.yml/build
#   SBOM_PATH               — path to sbom.cdx.json (downloaded artifact)
#   SLSA_PROVENANCE_URL     — URL to the .intoto.jsonl provenance asset
#   SIGSTORE_BUNDLE         — Sigstore signing bundle ref (set by publish job)
#   PRIVATE_REPO_READ_TOKEN — fine-grained PAT, read-only, single path on
#                             ghantakiran/ShieldOps; used to resolve the
#                             matching private source SHA from
#                             tools/SDK_TREE_PINS.txt.
#
# Output:
#   RELEASE_EVIDENCE.md in repo root, then `gh release upload`'d.

set -euo pipefail

: "${GITHUB_REF_NAME:?}"
: "${GITHUB_SHA:?}"
: "${SDK_VERSION:?}"
: "${SDIST_SHA256:?}"
: "${WHEEL_SHA256:?}"

# Optional with sensible defaults so the script is testable locally.
IS_RC="${IS_RC:-false}"
SBOM_PATH="${SBOM_PATH:-sbom.cdx.json}"
SLSA_PROVENANCE_URL="${SLSA_PROVENANCE_URL:-pending}"
SIGSTORE_BUNDLE="${SIGSTORE_BUNDLE:-pending}"

# Resolve the matching private-source SHA from tools/SDK_TREE_PINS.txt
# on the private monorepo using the single-path read-only PAT. The pin
# file is the only file this token can read.
PRIVATE_SOURCE_SHA="unknown"
if [[ -n "${PRIVATE_REPO_READ_TOKEN:-}" ]]; then
    PINS=$(curl -sf \
        -H "Accept: application/vnd.github.raw" \
        -H "Authorization: Bearer ${PRIVATE_REPO_READ_TOKEN}" \
        "https://api.github.com/repos/ghantakiran/ShieldOps/contents/tools/SDK_TREE_PINS.txt" \
        || echo "")
    if [[ -n "${PINS}" ]]; then
        PRIVATE_SOURCE_SHA=$(echo "${PINS}" \
            | awk -v ver="${SDK_VERSION}" '
                $0 ~ "^sdk-v"ver"$" { found=1; next }
                found && /^private_main_sha:/ { print $2; exit }
            ' || echo "lookup-failed")
    fi
fi

SBOM_DIGEST="unknown"
if [[ -f "${SBOM_PATH}" ]]; then
    SBOM_DIGEST=$(sha256sum "${SBOM_PATH}" | cut -d' ' -f1)
fi

cat > RELEASE_EVIDENCE.md <<EOF
# Release Evidence — ${GITHUB_REF_NAME}

This file is auto-generated by .github/scripts/assemble_release_evidence.sh.
Schema is forward-compatible with the PRD-013 Merkle ledger.

| Field | Value |
|---|---|
| Tag | \`${GITHUB_REF_NAME}\` |
| SDK version | \`${SDK_VERSION}\` |
| Release candidate | \`${IS_RC}\` |
| Public release SHA | \`${GITHUB_SHA}\` |
| Private source SHA | \`${PRIVATE_SOURCE_SHA}\` |
| sdist SHA-256 | \`${SDIST_SHA256}\` |
| wheel SHA-256 | \`${WHEEL_SHA256}\` |
| SBOM (CycloneDX) digest | \`${SBOM_DIGEST}\` |
| SLSA provenance | ${SLSA_PROVENANCE_URL} |
| Sigstore bundle | ${SIGSTORE_BUNDLE} |
| Generated at | $(date -u +%Y-%m-%dT%H:%M:%SZ) |

## Verifying this release

\`\`\`bash
# Verify the wheel matches the published artifact
pip download --no-deps shieldops-sdk==${SDK_VERSION} -d /tmp/verify
sha256sum /tmp/verify/shieldops_sdk-*.whl  # should match wheel SHA-256 above

# Verify Sigstore signature (after PR β #647 lands)
python -m sigstore verify identity \\
    --bundle "\${SIGSTORE_BUNDLE_PATH}" \\
    --cert-identity-regexp '^https://github.com/shieldops-io/shieldops-sdk/' \\
    --cert-oidc-issuer https://token.actions.githubusercontent.com \\
    /tmp/verify/shieldops_sdk-*.whl

# Verify SLSA provenance via slsa-verifier
slsa-verifier verify-artifact /tmp/verify/shieldops_sdk-*.whl \\
    --provenance-path provenance.intoto.jsonl \\
    --source-uri github.com/shieldops-io/shieldops-sdk \\
    --source-tag ${GITHUB_REF_NAME}
\`\`\`
EOF

echo "RELEASE_EVIDENCE.md written:"
cat RELEASE_EVIDENCE.md
